BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "FORMAÇÃO" (
	"CURSO"	TEXT,
	"IDENTIFICADOR FORMAÇÃO"	INTEGER NOT NULL,
	"IDENTIFICADOR SOBRE MIM"	INTEGER,
	PRIMARY KEY("IDENTIFICADOR FORMAÇÃO"),
	FOREIGN KEY("IDENTIFICADOR SOBRE MIM") REFERENCES "SOBRE MIM"("IDENTIFICADOR SOBRE MIM")
);
CREATE TABLE IF NOT EXISTS "SOBRE MIM" (
	"NOME"	TEXT,
	"TELEFONE"	TEXT,
	"IDENTIFICADOR SOBRE MIM"	INTEGER NOT NULL,
	"LOCALIZAÇÃO"	TEXT,
	"EMAIL"	TEXT NOT NULL,
	PRIMARY KEY("IDENTIFICADOR SOBRE MIM")
);
CREATE TABLE IF NOT EXISTS "HABILIDADES" (
	"ILLUSTRATOR"	TEXT,
	"PHOTOSHOP"	TEXT,
	"COREL DRAW"	TEXT,
	"DREAMWAVER"	TEXT,
	"HTML/CSS3"	TEXT,
	"IDENTIFICADOR HABILIDADES"	INTEGER NOT NULL,
	"IDENTIFICADOR SOBRE MIM"	INTEGER,
	PRIMARY KEY("IDENTIFICADOR HABILIDADES"),
	FOREIGN KEY("IDENTIFICADOR SOBRE MIM") REFERENCES "SOBRE MIM"("IDENTIFICADOR SOBRE MIM")
);
CREATE TABLE IF NOT EXISTS "PERSONALIDADE" (
	"LOREM IPSUM"	INTEGER,
	"IDENTIFICADOR PERSONALIDADE"	INTEGER NOT NULL,
	"IDENTIFICADOR SOBRE MIM"	INTEGER,
	CONSTRAINT "unq_PERSONALIDADE_LOREM IPSUM" UNIQUE("LOREM IPSUM"),
	PRIMARY KEY("IDENTIFICADOR PERSONALIDADE"),
	FOREIGN KEY("IDENTIFICADOR SOBRE MIM") REFERENCES "SOBRE MIM"("IDENTIFICADOR SOBRE MIM")
);
CREATE TABLE IF NOT EXISTS "EXPERIÊNCIA" (
	"NOME DA EMPRESA"	INTEGER,
	"IDENTIFICADOR EXPERIENCIA"	INTEGER NOT NULL,
	"IDENTIFICADOR SOBRE MIM"	INTEGER,
	PRIMARY KEY("IDENTIFICADOR EXPERIENCIA"),
	FOREIGN KEY("IDENTIFICADOR SOBRE MIM") REFERENCES "SOBRE MIM"("IDENTIFICADOR SOBRE MIM")
);
CREATE TABLE IF NOT EXISTS "REALIZAÇÕES" (
	"LOREM IPSUM"	TEXT,
	"IDENTIFICADOR  REALIZAÇÕES"	INTEGER NOT NULL,
	"IDENTIFICADOR SOBRE MIM"	INTEGER,
	PRIMARY KEY("IDENTIFICADOR  REALIZAÇÕES"),
	FOREIGN KEY("IDENTIFICADOR SOBRE MIM") REFERENCES "SOBRE MIM"("IDENTIFICADOR SOBRE MIM")
);
CREATE UNIQUE INDEX IF NOT EXISTS "pk_FORMAÇÃO" ON "FORMAÇÃO" (
	"IDENTIFICADOR FORMAÇÃO"
);
CREATE UNIQUE INDEX IF NOT EXISTS "unq_PERSONALIDADE_LOREM IPSUM" ON "PERSONALIDADE" (
	"LOREM IPSUM"
);
COMMIT;
